# site settings
title: '<%= Title %>'
email: '<%= Email %>'
description: 'Mauris facilisis fringilla elit, nec dapibus diam. Praesent sodales tortor eu risus elementum dignissim. Nunc feugiat quam sed orci tincidunt faucibus.'
baseurl: '//argentina.agendatransparencia.cl' #example: '/agendatransparencia'
basedomain: argentina.agendatransparencia.cl #ciudadanointeligente.github.io
analytics: '<%= GoogleAnalitycs %>'

# social
hashtags: AgendaTransparencia
twitter_username: <%= Twitter %>
twitter_txt: 'Maecenas purus neque, laoreet in lectus eget. '

#github
github_repo: '//github.com/<%= UserOrganization %>/<%= Repo %>'

# build settings
markdown: kramdown

collections:
  cards:
    output: true
